### ISSUE TITLE
Possibility to retrieve end_date

### ISSUE THREAD

**Issue by rafaltrojanowski** [sue445/google_holiday_calendar#17]
Hi @sue445 !

First of all, great gem! That saves tons of work.

This is not critical because I found a workaround for it, but I am wondering if that would be possible to return end_date somehow? I'm afraid that it would be a breaking change, what do you think?

In short: If Google Calendar API always returns ```end_date = start_date + 1``` it should not be a problem, I just have checked it for Thai holidays and it's valid.

**Comment by sue445** [comment]
@rafaltrojanowski You are correct. I can't remember why I wrote this :sweat_smile:
And I couldn't find  holiday calendar always returns `end_date = start_date + 1`.

But I have not seen the problem for 5 years. This is maybe no problem.

> Thai holidays and it's valid

Japan too.

**Comment by rafaltrojanowski** [comment]
@sue445 

> And I couldn't find holiday calendar always returns end_date = start_date + 1.

I meant about this part of the response:

```
"start": {
   "date": "2019-01-01"
},
"end": {
   "date": "2019-01-02"
},

```

Anyway, I think it's not a big thing, I'm closing.
