### ISSUE TITLE
Add more instructions for bash usage

### ISSUE THREAD

**Issue by rafaltrojanowski** [sue445/google_holiday_calendar#18]
Hi!

I have tried to run ```google_holiday_calendar``` and I have difficulty to understand how api_key is injected to make it work correctly. Could you please add some info to Docs? Thanks.

**Comment by sue445** [comment]
@rafaltrojanowski  I'll write a doc after RubyKaigi.

Thank you.

**Comment by rafaltrojanowski** [comment]
Thanks for quick reply, looking forward! 😄

**Comment by sue445** [comment]
@rafaltrojanowski This is resolved at #19 and #20. I released `v0.1.1`

**Comment by rafaltrojanowski** [comment]
Docs are great! Big thanks.
